# Dataset
name: CIFAR100
root: ./data

img_size: 32
num_classes: 100

global_crop_ratio: !!python/tuple [0.32, 1.0]
local_crop_ratio: !!python/tuple [0.05, 0.32]
local_crop_size: 8
nb_local_crops: 8

dataset_means: [0.4914, 0.4822, 0.4465]
dataset_stds: [0.2023, 0.1994, 0.2010]
