# Model
backbone_model: vit_tiny
patch_size: 4
optimizer: adamw
out_dim: 1024

teacher_temp: 0.04
teacher_momentum: 0.996
student_temp: 0.1
center_momentum: 0.9

# Training
warmup_epochs: 5
epochs: 20
batch_size: 128
start_lr: 5e-5
min_lr: 1e-6
weight_decay: 0.04
weight_decay_end: 0.4

# Misc
seed: 42
checkpoint_freq: 10
checkpoint_dir: "./logs/"
